FROM registry.redhat.io/ubi9/go-toolset:9.7@sha256:799cc027d5ad58cdc156b65286eb6389993ec14c496cf748c09834b7251e78dc AS builder

USER 0
WORKDIR /app

ENV GOTOOLCHAIN=auto

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ cmd/
COPY pkg/ pkg/
COPY internal/ internal/

RUN CGO_ENABLED=1 GOOS=linux go build -ldflags="-s -w" -o /usr/local/bin/model-signing ./cmd/model-signing

FROM registry.access.redhat.com/ubi9-minimal@sha256:c7d44146f826037f6873d99da479299b889473492d3c1ab8af86f08af04ec8a0 AS deploy

COPY --from=builder /usr/local/bin/model-signing /usr/local/bin/model-signing
COPY LICENSE /licenses/license.txt

USER 65532:65532

ENTRYPOINT ["model-signing"]
CMD ["--help"]

LABEL description="Supply chain security for ML"
LABEL io.k8s.description="Supply chain security for ML"
LABEL io.k8s.display-name="Model Transparency Library"
LABEL io.openshift.tags="model transparency security ml"
LABEL summary="Provides a library for model transparency."
LABEL com.redhat.component="model-transparency"
LABEL name="rhtas/model-transparency-rhel9"
LABEL cpe="cpe:/a:redhat:trusted_artifact_signer:1.3.1::el9"
